import Head from 'next/head';
import { Inter } from 'next/font/google';
import { useEffect, useState } from 'react';
import TodoList from '@/TodoList';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const API_ENDPOINT = "https://backend-rnkp.api.codehooks.io/dev/flashCard/";
  const API_KEY = "10772928-f01a-46be-b1b6-a67f7d64d93b";

  const [posts, setPosts] = useState(null);
  const [loading, setLoading] = useState(true);

  const [todos, setTodos] = useState([{item: "Buy chicken nuggets"},
                                      {item: "Eat chicken nuggets"}]);

  useEffect(() => {
    const fetchData = async () => {
      const response = await fetch(API_ENDPOINT, {
        'method':'GET',
        'headers': {'x-apikey': API_KEY}
      })
      const data = await response.json()
      // update state -- configured earlier.
      setPosts(data);
      setLoading(false);
    }
    fetchData();
  }, [])

  if(loading) {
    return (<span> Loading... </span>);
  } else {
    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <div>
            <p>
              {posts[0].front}
            </p>
          </div>
        </main>
        <TodoList todos={todos}></TodoList>
      </>
    );
  }
}
